 services:
   postgres:
     container_name: postgres-sql-auth
     image: postgres
     environment:
       POSTGRES_USER: username
       POSTGRES_PASSWORD: password
       PGDATA: /var/lib/postgresql/data
       POSTGRES_DB: auth_db
    #volumes:
     #  - postgres:/data/postgres

volumes:
  postgres: